//ARRAYS:
var frutas = ["Manzana", "Plátano", "Cereza", "Fresa"]; //FORMA DE SINTAXIS DE UN ARRAY
//EN ESTE CASO, EL ARRAY FRUTAS ES DE TIPO STRING, YA QUE TODOS SUS ELEMENTOS INTERNOS SON STRING

console.log(frutas);//MOSTRARÁ EN CONSOLA TODOS LOS STRINGS DENTRO DEL ARRAY:
//"Manzana", "Plátano", "Cereza", "Fresa"

console.log(frutas.length) //MOSTRARÁ EN CONSOLA LA DIMENSIÓN DEL ARRAY. ES DECIR, EL NUMERO DE OBJETOS QUE TIENE
//4

console.log(frutas[0]); //MOSTRARÁ "MANZANA"
console.log(frutas[1]); //MOSTRARÁ "PLÁTANO"
console.log(frutas[2]); //MOSTRARÁ "CEREZA"
console.log(frutas[3]); //MOSTRARÁ "FRESA"

/*
CADA OBJETO DENTRO DEL ARRAY SE CUENTA A PARTIR DEL 0. SI EL ARRAY TIENE 4 OBJETOS, EL PRIMER OBJETO
SERÁ DE INDICE 0, EL SEGUNDO DE INDICE 1, EL TERCERO DE INDICE 2 Y EL CUARTO DE INDICE 3
*/

//AGREGAR MAS OBJETOS AL ARRAY
frutas.push("Uvas"); //SE AGREGA EL OBJETO "UVAS" AL ARRAY FRUTAS

console.log(frutas); //AHORA CON EL NUEVO OBJETO AGREGADO, EL ARRAY ES EL SIGUIENTE:
//"Manzana", "Plátano", "Cereza", "Fresa", "Uvas"

/*
AHORA QUE SE HA AGREGADO EL NUEVO OBJETO, SE POSICIONARÁ AL FINAL DE TODOS LOS ELEMENTOS ANTERIORMENTE
AGREGADOS. ESTO DA COMO RESULTADO QUE EL OBJETO "UVAS" SEA DE ÍNDICE 4
*/

console.log(frutas[4]); //MOSTRARÁ "UVAS"

//ELIMINAR OBJETOS AL ARRAY
frutas.pop["Uvas"]; //SE ELIMINARÁ EL OBJETO "UVAS" DEL ARRAY

//AGREGAR UN NUEVO OBJETO PERO NO AL FINAL DEL ARRAY, SINO AL INICIO
frutas.unshift("Uvas"); 

frutas.shift("Uvas");

//PARA CONOCER LA POSICIÓN DE UN OBJETO DENTRO DEL ARRAY
frutas.indexOf("Cereza"); //ÉSTO DEVOLVERÁ EL INDICE EN DONDE SE ENCUENTRE EL OBJETO "CEREZA"
//2