
//BUCLE FOR
var estudiantes = ["Maria", "Sergio", "Rosa", "Daniel"];

/*EL CONTADOR DEL BUCLE INICIA EN 0; SE REALIZARÁ UN NÚMERO DE ITERACIONES IGUAL AL NUMERO DE OBJETOS DENTRO DEL ARRAY
  SE VA HACIENDO DE ITERACIÓN EN ITERACIÓN.
*/
for(var i = 0; i < estudiantes.length; i++){
    //TODO EL CÓDIGO AQUI DENTRO SE REPETIRÁ N VECES, DEPENDIENDO DE CUANTAS ITERACIONES HARÁ EL BUCLE
    console.log(estudiantes[i]);
}

//BUCLE WHILE
var controlBucle = 0;
/* EL BUCLE WHILE HARÁ ITERACIONES MIENTRAS QUE LA CONDICIÓN QUE ESTÉ ADENTRO DEL WHILE
   SE SIGA CUMPLIENDO. UNA VEZ QUE LA CONDICIÓN DEL WHILE DEJE DE CUMPLIRSE, EL BUCLE SE ROMPERÁ.

   EN ÉSTE CASO, LA CONDICIÓN ES QUE EL BUCLE SE SIGA REPITIENDO MIENTRAS QUE LA VARIABLE
   CONTROLBUCLE SEA MENOR AL TAMAÑO DEL ARRAY ESTUDIANTES, ES DECIR, MENOR A 4.

   LA VARIABLE CONTROLBUCLE INICIA EN 0, POR LO QUE EN LA PRIMERA ITERACIÓN SE VERIFICARÁ ÉSTA CONDICIÓN:

   0 (controlBucle) ES MENOR A 4(estudiantes.length)?
   RESPUESTA: SI, POR LO TANTO, SE HARÁ LA PRIMERA ITERACIÓN. SE EJECUTARÁN LAS 2 LINEAS DE CODIGO DENTRO DEL WHILE.

   UNA VEZ EJECUTADA LA LINEA "controlBucle ++;" DENTRO DEL WHILE, SE LE SUMARÁ UN NUMERO A LA VARIABLE CONTROLBUCLE,
   ES DECIR, YA NO ES 0, SINO AHORA ES 1. CON ÉSTE NUEVO VALOR VOLVEMOS A VERIFICAR LA CONDICIÓN:

   1 (controlBucle) ES MENOR A 4(estudiantes.length)?
   RESPUESTA: SI, POR LO TANTO SE HARÁ LA SEGUNDA ITERACIÓN.

   Y ASÍ SUCESIVAMENTE HASTA QUE LA VARIABLE CONTROLBUCLE SEA = 4, YA QUE AL SER IGUAL A 4, NO SE CUMPLIRÁ CON LA CONDICIÓN:
   "controlBucle < estudiantes.length" Y POR LO TANTO LAS ITERACIONES TERMINARÁN
*/ 
while (controlBucle < estudiantes.length){
    console.log(estudiantes[i]);
    controlBucle ++;
}