//HOISTING

//IMPRIMIMOS EN CONSOLA LA VARIABLE AUN NO DECLARADA 
console.log(miNombre);

//LUEGO DECLARAMOS E INICIALIZAMOS LA VARIABLE
var miNombre = "Diego";

/* AL HACER ESTO, JS DETECTA QUE LO QUE ESTÁ DENTRO DEL CONSOLE.LOG ES UNA
   VARIABLE, Y POR LO TANTO LA INICIALIZA AL INICIO DEL CÓDIGO DE LA SIGUIENTE
   MANERA:
*/

var miNombre = undefined;

/* POR LO TANTO, LO QUE SE IMPRIMIRÁ EN EL CONSOLE LOG SERÁ "UNDEFINED", EN 
   VEZ DE LANZAR UN ERROR EN EL QUE SE DIGA QUE LA VARIABLE NO EXISTE.
*/

//SE PUEDE REALIZAR LO MISMO CON FUNCIONES:

funcion();

function funcion(){
    console.log("Hola " + miNombre);
}

var miNombre = "David";

/* ESTAMOS LLAMANDO A LA FUNCIÓN "FUNCION()" ANTES DE DECLARARLA. COMO EN EL
   CASO DE LAS VARIABLES, CON LAS FUNCIONES TAMPOCO SALE ERROR, SINO QUE JS
   INTERPRETA EL LLAMADO DE LA FUNCIÓN Y LA CREA.
*/
