//EJEMPLOS EN LOS QUE BOOLEAN DEVUELVE "FALSE":
Boolean(0);
Boolean(null);
Boolean(NaN);
Boolean(undefined);
Boolean(false);
Boolean("");

//EJEMPLOS EN LOS QUE BOOLEAN DEVUELVE "TRUE":
Boolean(1); //TRUE PARA 1 O PARA CUALQUIER NUMERO DIFERENTE DE CERO (0)
Boolean("a"); //TRUE PARA CUALQUIER CARACTER O ESPACIO EN BLANCO EN STRING
Boolean([]); //TRUE AUNQUE EL ARRAY ESTÉ VACÍO
Boolean({}) //TRUE AUNQUE EL OBJETO ESTÉ VACÍO
Boolean(function(){}); //CUALQUIER FUNCION ES VERDADERA